[tool.poetry]
name = "ml-batch-system-feature-pipeline"
version = "1.0.0"
description = "Feature Pipeline Module"
authors = [
    "Roberto Hernandez <betohr60@gmail.com>"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ipykernel = "6.21.*"
pandas = "^2.0.3"
hopsworks = "^3.4.3"
